export type TNote = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
  | 'A♯' | 'C♯' | 'D♯' | 'F♯' | 'G♯'
  | 'A#' | 'C#' | 'D#' | 'F#' | 'G#'
  | 'A♭' | 'B♭' | 'D♭' | 'E♭' | 'G♭'
  | 'Ab' | 'Bb' | 'Db' | 'Eb' | 'Gb'
