import { getChordType } from 'src/app/components/chord-highlighter/data/chords'
import fs from 'fs'

const file: string = 'src/app/components/chord-highlighter/types/t-chord.ts'

console.log(`writing file ${file}\n`)

const chordType: string = getChordType()

const content: string = `// file generated by running ... npm run gen-chord-type
export type TChord = ${chordType}
`

fs.writeFileSync(file, content)

console.log(content)
